# Generated by Django 4.1.2 on 2023-03-07 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('school', models.CharField(max_length=100)),
                ('fullfilment_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
